#!/usr/bin/env bash
# OpenEOC single-node installer (VEOC-40). Aimed at county-IT skill levels:
# it checks prerequisites, generates secrets on first run, brings the stack
# up, waits for health, and prints the next step. Idempotent and safe to
# re-run. Works air-gapped when the images are already present locally
# (see deploy/README.md).
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$here"

say() { printf '\n\033[1m[openeoc]\033[0m %s\n' "$*"; }
fail() { printf '\n\033[31m[openeoc] %s\033[0m\n' "$*" >&2; exit 1; }

command -v docker >/dev/null 2>&1 || fail "docker is required. Install Docker Engine, then re-run."
docker compose version >/dev/null 2>&1 || fail "the docker compose plugin is required."

new_password() { head -c 24 /dev/urandom | base64 | tr -d '/+=' | head -c 32; }

# First-run secrets land in .env; re-runs keep the existing ones.
if [ ! -f .env ]; then
  say "First run: generating secrets into deploy/.env"
  secret="$(head -c 32 /dev/urandom | base64 | tr -d '/+=' | head -c 44)"
  cat > .env <<EOF
# Generated by install.sh on first run. Keep this file secret and backed up.
OPENEOC_DB_PASSWORD=$(new_password)
OPENEOC_SECRET_KEY=$secret
EOF
  chmod 600 .env
else
  say "Reusing existing deploy/.env"
fi

# The API serves as app_runtime so Row-Level Security applies, and refuses to
# start without it. An .env from an older install gains the role's URL here.
set -a; . ./.env; set +a
if [ -z "${OPENEOC_RUNTIME_URL:-}" ]; then
  OPENEOC_RUNTIME_PASSWORD="$(new_password)"
  OPENEOC_RUNTIME_URL="postgres://app_runtime:$OPENEOC_RUNTIME_PASSWORD@db:5432/openeoc"
  { grep -v '^OPENEOC_RUNTIME_URL=' .env || true
    echo "OPENEOC_RUNTIME_PASSWORD=$OPENEOC_RUNTIME_PASSWORD"
    echo "OPENEOC_RUNTIME_URL=$OPENEOC_RUNTIME_URL"
  } > .env.new
  chmod 600 .env.new
  mv .env.new .env
fi

say "Starting the database"
docker compose up -d db

say "Waiting for the database to be healthy"
for _ in $(seq 1 40); do
  if docker compose exec -T db pg_isready -U openeoc_owner -d openeoc >/dev/null 2>&1; then
    break
  fi
  sleep 3
done

if [ -n "${OPENEOC_RUNTIME_PASSWORD:-}" ]; then
  say "Setting the app_runtime password"
  docker compose exec -T db psql -v ON_ERROR_STOP=1 -U openeoc_owner -d openeoc \
    -v pw="$OPENEOC_RUNTIME_PASSWORD" >/dev/null <<'SQL'
select 'create role app_runtime login'
  where not exists (select from pg_roles where rolname = 'app_runtime') \gexec
alter role app_runtime login password :'pw';
SQL
fi

say "Building and starting the API"
docker compose up -d --build

say "Waiting for the API to answer"
for _ in $(seq 1 40); do
  if curl -fsS "http://localhost:8080/api/v1/me" >/dev/null 2>&1; then break; fi
  # 401 is a healthy answer from an auth-gated endpoint.
  code="$(curl -s -o /dev/null -w '%{http_code}' "http://localhost:8080/api/v1/me" || true)"
  [ "$code" = "401" ] && break
  sleep 3
done

say "Up. API on http://localhost:8080"
say "Next: create the first jurisdiction and admin with the bootstrap command"
say "(see deploy/README.md, 'First jurisdiction and admin')."
