-- Short numbers for resource requests and incident tasks.
--
-- Operators name work by number on the radio and in briefings ("REQ-1027",
-- "TASK-204"). Each table draws its numbers from its own identity sequence;
-- existing rows are numbered in the order the column fills them. A number is
-- a reference, not an order of work, and is never reused.

alter table public.resource_requests
  add column number bigint generated by default as identity (start with 1001);
create unique index resource_requests_number on public.resource_requests (number);

alter table public.checklist_items
  add column number bigint generated by default as identity (start with 201);
create unique index checklist_items_number on public.checklist_items (number);
